### ISSUE TITLE
ModuleNotFoundError: No module named 'pymongo'

### ISSUE THREAD

**Issue by corenting** [python-cachier/cachier#125]
Hello !

I'm seeing a regression on the latest version when not using pymongo.
In `core.py`, an import for pymongo was added for type hints: https://github.com/python-cachier/cachier/blob/50fb9dafaa7f8d127bca738d07165054d82e910d/cachier/core.py#L23

However the case where pymongo is not installed is not handled, which results in a 
`ModuleNotFoundError: No module named 'pymongo'` when importing cachier without pymongo.

**Comment by cthoyt** [comment]
hi @corenting, I also experienced this issue and sent a PR in #126 with a fix.

**Comment by shaypal5** [comment]
A solution by the venerable @cthoyt was released in `v2.2.1`.

**Comment by corenting** [comment]
Thanks for the quick fix and the new release !
