### ISSUE TITLE
Make kwargs hashing order independent 

### ISSUE THREAD

**Issue by levitation** [python-cachier/cachier#132]
I suggest to sort kwargs so that changing the ordering will not invalidate the cache
kwargs_ordered = OrderedDict(sorted(kwargs.items()))

**Comment by shaypal5** [comment]
Sounds good! Do you want to open a PR with the change yourself?
@levitation

**Comment by levitation** [comment]
Opened PR https://github.com/python-cachier/cachier/pull/133

**Comment by shaypal5** [comment]
Solved by PRs #133 , #134 and #138
