### ISSUE TITLE
workaround for `TypeError: unhashable type: 'list'`

### ISSUE THREAD

**Issue by Borda** [python-cachier/cachier#136]
Hello, I think that `list` as an argument is quite often, so how about hashing and converting it internally for hashing only to `tuple`, where the order is preserved... what do you think about adding it to the codebase?

**Comment by shaypal5** [comment]
Well, as I've written in the related issue, it sounds very relevant, but has to be thoroughly tested and benchmarked.

HOWEVER, in the mean time, please note you can easily work around this using custom hashing logic, which `cachier` supports: 😄 
https://github.com/python-cachier/cachier?tab=readme-ov-file#working-with-unhashable-arguments
