### ISSUE TITLE
switch from `wearerequired/lint-action` to `pre-commit`

### ISSUE THREAD

**Issue by Borda** [python-cachier/cachier#137]
From my practical experience, it is suitable for a developer to be able to run all lint locally, which seems not to be possible with the used `wearerequired/lint-action` (which also integrated multiple tools) compared to suggested pre-commit, which has more options for possible customization. Alternatively, there is a free [bot](https://github.com/marketplace/pre-commit-ci) that can perform some minor fixes instead of the contributor... :rabbit: If you are interested, I am happy to send a PR with this enhancement :flamingo:

**Comment by shaypal5** [comment]
I'd love too, yes! Thank you! 🐐

**Comment by Borda** [comment]
@shaypal5 could you install the https://github.com/marketplace/pre-commit-ci for this repo so it will guard the code quality :pray:

**Comment by shaypal5** [comment]
Done.
