### ISSUE TITLE
We currently do not have an orderly release process

### ISSUE THREAD

**Issue by shaypal5** [python-cachier/cachier#158]
Would love to hear your thoughts on this, @Borda .

I currently release from master manually, from my personal laptop, when a bugfix or a feature is pulled in (and let nice-to-have changes, documentation, etc. wait in master until the next functionality-affecting change).

Do we want to build an automated process for building and releasing the package to PyPI? I'm assuming git and Github have relevant abilities; maybe something that also tests the packages files, and then some approval by a certain class of contributors? With PyPI credentials loaded as repository secrets and used by the deploy job to deploy to PyPI?

I'm just guessing here. I don't mind carry on as it is now; just thought to ask.

**Comment by Borda** [comment]
> Do we want to build an automated process for building and releasing the package to PyPI?

In general, it shall be fine and straightforward, except I do not have any experience with Versioneer, could you pls describe the steps you do manually? :robot: 
Then the automation shall be fine with for example GH release of git tag... :rocket:
