### ISSUE TITLE
Cachier caches a None return value when a function raises an Exception

### ISSUE THREAD

**Issue by shaypal5** [python-cachier/cachier#215]
I notice this caches "None" when the function raises an Exception. Eg:
```py
@cachier.cachier(backend='memory',allow_none=True)
def tmp_test(a):
    raise Exception()

tmp_test(123)  # Raises Exception
tmp_test(123)  # Returns None
```

Is this WAI?

_Originally posted by @tashmore in https://github.com/python-cachier/cachier/issues/121#issuecomment-2098803095_

**Comment by Borda** [comment]
is it only for `backend='memory'` or all backends?
